---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
- name: pack-release
- name: ci-src

outputs:
- name: docker-build-args

run:
  path: ci-src/ci/tasks/generate-docker-build-args/generate-docker-build-args.sh