---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
- name: pack-release
- name: src

outputs:
- name: docker-build-args

run:
  path: src/ci/tasks/generate-docker-build-args/generate-docker-build-args.sh