resources:
- name: pack-release
  type: github-release
  source:
    owner: buildpack
    repository: pack
    access_token: ((github.access-token))
- name: src
  type: git
  source:
    uri: ((concourse-pack.git.uri))
    private_key: ((concourse-pack.git.private-key))
    branch: master
- name: pack-docker-image
  type: docker-image
  source:
    repository: daniellavoie/pack-resource
    username: ((dockerhub.username))
    password: ((dockerhub.password))

jobs:
- name: Build Pack Docker Image
  plan:
  - get: pack-release
    trigger: true
  - get: src
  - task: Generate Docker Build Args
    file: src/ci/tasks/generate-docker-build-args/generate-docker-build-args.yml
  - put: pack-docker-image
    params:
      build: src/ci/docker
      tag_file: pack-release/version
      build_args_file: docker-build-args/docker-build-args.json